=== fodor-marcell/OREG3HWebXML/OREG3H_1014/OREG3H_vendeglatas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="etterem" type="etteremTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="foszakacs" type="foszakacsTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="szakacs" type="szakacsTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="gyakornok" type="gyakornokTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="vendeg" type="vendegTipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="etterem_kulcs">
            <xs:selector xpath="etterem"/>
            <xs:field xpath="@ekod"/>
        </xs:key>

        <xs:key name="foszakacs_kulcs">
            <xs:selector xpath="foszakacs"/>
            <xs:field xpath="@fkod"/>
        </xs:key>

        <xs:key name="szakacs_kulcs">
            <xs:selector xpath="szakacs"/>
            <xs:field xpath="@szkod"/>
        </xs:key>

        <xs:key name="gyakornok_kulcs">
            <xs:selector xpath="gyakornok"/>
            <xs:field xpath="@gykod"/>
        </xs:key>

        <xs:key name="vendeg_kulcs">
            <xs:selector xpath="vendeg"/>
            <xs:field xpath="@vkod"/>
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs" >
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@e_v_e"/>
        </xs:keyref>
        <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs" >
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@e_v_v"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs" >
            <xs:selector xpath="foszakacs"/>
            <xs:field xpath="@e_f"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs" >
            <xs:selector xpath="szakacs"/>
            <xs:field xpath="@e_s"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs" >
            <xs:selector xpath="gyakornok"/>
            <xs:field xpath="@e_gy"/>
        </xs:keyref>

        <!-- Az 1:1 kapcsolat megvalósításához -->
        <xs:unique name="unique_foszakacs">
            <xs:selector xpath="foszakacs"/>
            <xs:field xpath="@e_f"/>
        </xs:unique>
    </xs:element>

    <!-- Komplex típusok -->
    <xs:complexType name="etteremTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="cimTipus"/>
            <xs:element name="csillag" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="ekod" type="xs:string" use="required"/>
        <xs:attribute name="e_r" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:string" use="required"/>
        <xs:attribute name="e_f" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="reszleg" type="xs:string"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:string" use="required"/>
        <xs:attribute name="e_sz" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="gyakornokTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="gyakorlat" type="gyakorlatTipus"/>
            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:string" use="required"/>
        <xs:attribute name="e_gy" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="gyakorlatTipus">
        <xs:sequence>
            <xs:element name="kezdete" type="xs:string"/>
            <xs:element name="idotartama" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vendegTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="cim" type="cimTipus"/>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="osszeg" type="xs:integer"/>
            <xs:element name="etel" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="e_v_e" type="xs:string" use="required"/>
        <xs:attribute name="e_v_v" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== fodor-marcell/OREG3HWebXML/OREG3H_1014/OREG3H_xml.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="OREG3H_vendeglatas.xsd">
    <!-- Éttermek -->
    <etterem ekod="e1" e_r="e1">
        <nev>Valami étterem</nev>
        <cim>
            <varos>Miskolc</varos>
            <utca>Étterem utca</utca>
            <hazszam>123</hazszam>
        </cim>
        <csillag>4</csillag>
    </etterem>

    <etterem ekod="e2" e_r="e2">
        <nev>Másik étterem</nev>
        <cim>
            <varos>Debrecen</varos>
            <utca>Debreceni utca</utca>
            <hazszam>12345</hazszam>
        </cim>
        <csillag>4</csillag>
    </etterem>

    <!-- Főszakács -->
    <foszakacs fkod="f1" e_f="e1">
        <nev>Havas Péter</nev>
        <eletkor>35</eletkor>
        <vegzettseg>Szakközépiskola</vegzettseg>
        <vegzettseg>Institut Paul Bocuse</vegzettseg>
    </foszakacs>

    <foszakacs fkod="f2" e_f="e2">
        <nev>Kovács János</nev>
        <eletkor>40</eletkor>
        <vegzettseg>Szakiskola</vegzettseg>
    </foszakacs>

    <!-- Szakácsok -->
    <szakacs szkod="sz1" e_sz="e1">
        <nev>Kovács János</nev>
        <reszleg>Levesek</reszleg>
        <vegzettseg>Szakiskola</vegzettseg>
    </szakacs>

    <szakacs szkod="sz2" e_sz="e2">
        <nev>Szabó Máté</nev>
        <reszleg>Főétel</reszleg>
        <vegzettseg>Szakiskola</vegzettseg>
    </szakacs>

    <szakacs szkod="sz3" e_sz="e3">
        <nev>Kiss Erzsébet</nev>
        <reszleg>Desszert</reszleg>
        <vegzettseg>Szakiskola</vegzettseg>
    </szakacs>

    <!-- Gyakornokok -->
    <gyakornok gykod="gy1" e_gy="e1">
        <nev>Horvát Péter</nev>
        <gyakorlat>
            <kezdete>2023.08.20.</kezdete>
            <idotartama>2 honap</idotartama>
        </gyakorlat>
        <muszak>Délután</muszak>
    </gyakornok>

    <gyakornok gykod="gy2" e_gy="e2">
        <nev>Szilágyi István</nev>
        <gyakorlat>
            <kezdete>2023.08.20.</kezdete>
            <idotartama>2 honap</idotartama>
        </gyakorlat>
        <muszak>Délután</muszak>
    </gyakornok>

    <gyakornok gykod="gy3" e_gy="e3">
        <nev>Szentpétery Ferenc</nev>
        <gyakorlat>
            <kezdete>2023.01.01.</kezdete>
            <idotartama>10 honap</idotartama>
        </gyakorlat>
        <muszak>Délelőtt</muszak>
        <muszak>Délután</muszak>
    </gyakornok>

    <!-- Vendégek -->
    <vendeg vkod="v1">
        <nev>Fekete Péter</nev>
        <eletkor>21</eletkor>
        <cim>
            <varos>Miskolc</varos>
            <utca>Márton</utca>
            <hazszam>17</hazszam>
        </cim>
    </vendeg>

    <vendeg vkod="v2">
        <nev>Bordás Áron</nev>
        <eletkor>25</eletkor>
        <cim>
            <varos>Eger</varos>
            <utca>Dobó</utca>
            <hazszam>12</hazszam>
        </cim>
    </vendeg>

     <vendeg vkod="v3">
        <nev>Kiss Hajnalka</nev>
        <eletkor>26</eletkor>
        <cim>
            <varos>Miskolc</varos>
            <utca>Egyetem-város</utca>
            <hazszam>1</hazszam>
        </cim>
     </vendeg>

     <!-- Rendelés -->
    <rendeles e_v_e="e1" e_v_v="v1">
        <osszeg>20000</osszeg>
        <etel>Zsíros kenyér</etel>
    </rendeles>

    <rendeles e_v_e="e2" e_v_v="v1">
        <osszeg>300</osszeg>
        <etel>Mackó sajt</etel>
    </rendeles>

    <rendeles e_v_e="e2" e_v_v="v1">
        <osszeg>15000</osszeg>
        <etel>Kaviár</etel>
    </rendeles>
</vendeglatas>
